'use client';

import { FileDown, Loader2, RefreshCw } from 'lucide-react';
import Link from 'next/link';
import { useEffect, useRef } from 'react';
import { AppShell } from '@/components/layout/app-shell';
import { fetchAssignment } from '@/lib/api/assignments';
import { useGenerationStore } from '@/stores/generation-store';
import type { Assignment, QuestionPaper } from '@/types/assignment';

const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/api';

type Props = {
  assignmentId: string;
};

export function QuestionPaperShell({ assignmentId }: Props) {
  const { assignment, paper, status, progress, setSnapshot, setStatus, setProgress, reset } = useGenerationStore();
  const socketRef = useRef<{ disconnect: () => void } | null>(null);

  useEffect(() => {
    // Reset stale state when navigating to a different assignment
    reset();
    // Load the assignment (falls back to demo data if backend is down)
    void fetchAssignment(assignmentId).then(setSnapshot);

    // Attempt to connect to the socket – silently skip if the server is offline
    let cancelled = false;

    async function trySocket() {
      try {
        const { connectAssignmentSocket } = await import('@/lib/socket');
        if (cancelled) return;
        const socket = connectAssignmentSocket(assignmentId, {
          onStarted: () => setStatus('processing'),
          onProgress: (value) => setProgress(value),
          onCompleted: (payload) => {
            setStatus('completed');
            setSnapshot({ assignment: payload.assignment ?? assignment, paper: payload.paper });
          },
          onFailed: () => setStatus('failed')
        });
        socketRef.current = socket;
      } catch {
        // Socket server not available – demo mode is fine
      }
    }

    void trySocket();

    return () => {
      cancelled = true;
      socketRef.current?.disconnect();
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [assignmentId]);

  const visiblePaper = paper;
  const visibleStatus = status;

  return (
    <AppShell>
      <main className="mx-auto max-w-none">
        {/* Header bar */}
        <div className="rounded-[38px] bg-[#5B5B5B] p-2 lg:rounded-[36px] lg:p-7">
          <div className="no-print mb-2 rounded-[22px] bg-[#262626] px-4 py-5 text-white lg:mb-4 lg:rounded-[28px] lg:px-8 lg:py-7">
            <h1 className="max-w-[1080px] text-[11px] font-black leading-[1.35] tracking-[-0.02em] lg:text-lg">
              {assignment
                ? `Here is the AI-generated question paper for your ${assignment.classLevel} ${assignment.subject} class. Review and download below.`
                : 'Certainly! Here is your customised question paper generated by VedaAI.'}
            </h1>
            <div className="mt-5 flex flex-wrap items-center gap-3">
              <a
                href={`${apiUrl}/pdf/assignments/${assignmentId}`}
                className="inline-flex h-8 items-center gap-3 rounded-full bg-white px-3 text-[0px] font-bold text-[#333] lg:h-11 lg:px-6 lg:text-base"
              >
                <FileDown size={23} />
                Download as PDF
              </a>
              <Link
                href="/"
                className="inline-flex h-8 items-center gap-2 rounded-full border border-white/30 bg-white/10 px-3 text-[0px] font-bold text-white lg:h-11 lg:px-6 lg:text-sm"
              >
                ← All Assignments
              </Link>
            </div>
          </div>

          {visibleStatus !== 'completed' || !visiblePaper ? (
            <GenerationLoader status={visibleStatus} progress={progress} />
          ) : (
            <QuestionPaperPreview paper={visiblePaper} assignment={assignment} />
          )}
        </div>
      </main>
    </AppShell>
  );
}

function GenerationLoader({ status, progress }: { status: string; progress: number }) {
  const isFailure = status === 'failed';

  return (
    <div className="rounded-[28px] bg-white p-8 text-center shadow-card">
      <div className={`mx-auto flex h-14 w-14 items-center justify-center rounded-full ${isFailure ? 'bg-rose-100 text-rose-700' : 'bg-brand-50 text-brand-700'}`}>
        {isFailure ? (
          <RefreshCw className="h-7 w-7" />
        ) : (
          <Loader2 className="h-7 w-7 animate-spin" />
        )}
      </div>
      <h2 className="mt-5 text-lg font-semibold">
        {isFailure ? 'Generation failed' : 'Generating question paper…'}
      </h2>
      <p className="mt-2 text-sm text-neutral-500">
        {isFailure
          ? 'There was a problem generating the paper. You can try regenerating or go back.'
          : 'VedaAI is validating the structured response and preparing the exam layout.'}
      </p>
      {!isFailure && (
        <div className="mx-auto mt-6 h-2 max-w-md overflow-hidden rounded-full bg-neutral-100">
          <div className="h-full rounded-full bg-brand-500 transition-all" style={{ width: `${progress || 30}%` }} />
        </div>
      )}
      {isFailure && (
        <Link
          href="/"
          className="mt-6 inline-flex h-10 items-center gap-2 rounded-full bg-[#171717] px-6 text-sm font-bold text-white"
        >
          ← Back to Assignments
        </Link>
      )}
    </div>
  );
}

function QuestionPaperPreview({ paper, assignment }: { paper: QuestionPaper; assignment: Assignment | null }) {
  const totalMarks = paper.sections
    .flatMap((s) => s.questions)
    .reduce((sum, q) => sum + q.marks, 0);

  return (
    <article className="mx-auto min-h-[1250px] rounded-[26px] bg-white px-4 py-6 text-[#333] shadow-soft print:min-h-0 print:max-w-none print:shadow-none lg:rounded-[30px] lg:px-10 lg:py-9">
      <header className="pb-5 text-center">
        <h2 className="mx-auto max-w-[760px] text-[17px] font-black leading-tight tracking-[-0.04em] lg:text-[31px]">{paper.title}</h2>
        {assignment && (
          <>
            <p className="mt-6 text-[13px] font-black leading-none tracking-[-0.04em] lg:mt-3 lg:text-[22px]">
              Subject: {assignment.subject}
            </p>
            <p className="mt-2 text-[13px] font-black leading-none tracking-[-0.04em] lg:mt-3 lg:text-[22px]">
              Class: {assignment.classLevel}
            </p>
          </>
        )}
        <div className="mt-8 grid gap-2 text-left text-[11px] font-black lg:mt-9 lg:flex lg:justify-between lg:text-base">
          <span>Time Allowed: 3 hours</span>
          <span>Maximum Marks: {totalMarks}</span>
        </div>
      </header>

      <p className="mt-2 text-[11px] font-black lg:text-base">All questions are compulsory unless stated otherwise.</p>

      <section className="mt-7 space-y-1 text-[11px] font-black lg:text-base">
        <p>Name: ____________________</p>
        <p>Roll Number: _____________</p>
        <p>Class: {assignment?.classLevel ?? '___'} &nbsp; Section: __________</p>
      </section>

      <div className="mt-[40px] space-y-8">
        {paper.sections.map((section) => (
          <section key={section.title}>
            <div className="text-center">
              <h3 className="text-base font-black tracking-[-0.04em] lg:text-[24px]">{section.title}</h3>
            </div>
            <div className="mt-9">
              <p className="text-[11px] font-black lg:text-base">{section.instruction}</p>
            </div>
            <ol className="mt-5 space-y-[14px] lg:mt-9 lg:space-y-[18px]">
              {section.questions.map((question, index) => (
                <li key={`${section.title}-${index}`} className="text-[11px] leading-[1.45] lg:text-base">
                  <span>{index + 1}. </span>
                  <span>[{mapDifficulty(question.difficulty)}] </span>
                  <span>{question.question}</span>
                  <span> [{question.marks} {question.marks === 1 ? 'Mark' : 'Marks'}]</span>
                </li>
              ))}
            </ol>
          </section>
        ))}
      </div>

      <footer className="mt-6 text-[11px] font-black lg:text-base">
        *** End of Question Paper ***
      </footer>
    </article>
  );
}

function mapDifficulty(difficulty: 'Easy' | 'Medium' | 'Hard') {
  if (difficulty === 'Hard') return 'Challenging';
  if (difficulty === 'Medium') return 'Moderate';
  return difficulty;
}
